export const bookData = {
  id: "676fe9dd8d96eca5d7bee90d",
  title: "Physics for class 12th",
  price: 299,
  originalPrice: 500,
  shipping: "Shipping Available",
  posted: "less than a minute ago",
  subject: "Physics",
  course: "12th",
  category: "School Books (up to 12th)",
  author: "Rs agrawal",
  edition: "2th edition",
  condition: "excellent",
  description: "this is physics book for 12",
  seller: {
    name: "Dheeraj Agrahari",
    verified: true,
    location: "Mirzapur, UP",
    contact: "07807263566",
    email: "dheraj@yopmail.com",
  },
  images: [
    "https://www.shutterstock.com/image-photo/book-open-pages-close-up-600nw-2562942291.jpg",
    "https://d3i3lzopayriz.cloudfront.net/v3/book-files/9789355743749/front_img_cover.jpg",
    "/images/book_01.jpg",
    "/images/book_02.jpg",
  ],
};


export const books = [
  {
    id: 1,
    title: "Mathematics for 6th Class",
    price: 299,
    originalPrice: 400,
    discount: "25%",
    image: bookData?.images[0],
    category: "Mathematics",
    condition: "New",
  },
  {
    id: 2,
    title: "Mastering Advanced Data Structures",
    price: 899,
    originalPrice: 1200,
    discount: "25%",
    image: bookData?.images[1],
    category: "Computer Science",
    condition: "New",
    author: "Dr. Alan Turing",
    level: "Advanced",
  },
  {
    id: 3,
    title: "Quantum Physics: Beyond the Basics",
    price: 1099,
    originalPrice: 1400,
    discount: "22%",
    image: bookData?.images[2],
    category: "Physics",
    condition: "Used",
    author: "Dr. Richard Feynman",
    level: "Expert",
  },
  {
    id: 4,
    title: "The Magic of Mathematics: Secrets of Numbers",
    price: 749,
    originalPrice: 950,
    discount: "21%",
    image: bookData?.images[3],
    category: "Mathematics",
    condition: "New",
    author: "Marcus du Sautoy",
    level: "Intermediate",
  },
];

export const sampleOrders = [
  {
    id: "1001",
    name: "Product A",
    quantity: 2,
    status: "Pending",
    createdDate: "2025-09-10",
  },
  {
    id: "1002",
    name: "Product B",
    quantity: 1,
    status: "Delivered",
    createdDate: "2025-09-12",
  },
]