export const bookData = {
  id: "676fe9dd8d96eca5d7bee90d",
  title: "Physics for class 12th",
  price: 299,
  originalPrice: 500,
  shipping: "Shipping Available",
  posted: "less than a minute ago",
  subject: "Physics",
  course: "12th",
  category: "School Books (up to 12th)",
  author: "Rs agrawal",
  edition: "2th edition",
  condition: "excellent",
  description: "this is physics book for 12",
  seller: {
    name: "Dheeraj Agrahari",
    verified: true,
    location: "Mirzapur, UP",
    contact: "07807263566",
    email: "dheraj@yopmail.com",
  },
  images: [
    "https://www.shutterstock.com/image-photo/book-open-pages-close-up-600nw-2562942291.jpg",
    "https://d3i3lzopayriz.cloudfront.net/v3/book-files/9789355743749/front_img_cover.jpg",
  ],
};


export const books = [
  {
    id: 1,
    title: "Mathematics for 6th Class",
    price: 299,
    originalPrice: 400,
    discount: "25%",
    image: bookData?.images[0],
    category: "Mathematics",
    condition: "New",
  },
  {
    id: 2,
    title: "Physics for 6th Class",
    price: 349,
    originalPrice: 450,
    discount: "22%",
    image: bookData?.images[1],
    category: "Science",
    condition: "Used",
  },
  {
    id: 3,
    title: "Chemistry for 6th Class",
    price: 279,
    originalPrice: 350,
    discount: "20%",
    image: bookData?.images[0],
    category: "Science",
    condition: "New",
  },
  {
    id: 4,
    title: "Biology for 6th Class",
    price: 319,
    originalPrice: 400,
    discount: "20%",
    image: bookData?.images[1],
    category: "Science",
    condition: "Used",
  },
];